__default__:
    system: 'slurm'
    account: "132773335440"
    time: "12:00:00" # in minutes
    mem: "10g" # in GB
    threads: "10"
    queue: "xlong" # gpu
    nodes: "1" 

Assemble_rRNA:
    mem: "60g" # in GB
    threads: "28"   
 
Detect_chimeras:
    mem: "210g" # in GB
    threads: "28"    
    
BlastSeqs:
    mem: "60g" # in GB
    threads: "28"
    time: "17:00:00" 
